# Generated by Django 6.0.7 on 2026-09-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='UtensilsCrossed', max_length=50)),
                ('color', models.CharField(default='#f97316', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('product_id', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=150)),
                ('type', models.CharField(default='POS Deduction', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('previous_stock', models.IntegerField(default=0)),
                ('new_stock', models.IntegerField(default=0)),
                ('reason', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('token_no', models.CharField(default='T-01', max_length=20)),
                ('order_type', models.CharField(default='Dine In', max_length=30)),
                ('table_no', models.CharField(blank=True, default='Table 1', max_length=30)),
                ('customer_name', models.CharField(default='Walk-in Customer', max_length=100)),
                ('customer_phone', models.CharField(blank=True, default='9999999999', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(default='Cash', max_length=30)),
                ('payment_status', models.CharField(default='Paid', max_length=30)),
                ('cashier_name', models.CharField(default='Counter Staff', max_length=100)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('change_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='Completed', max_length=30)),
                ('items', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gst', models.IntegerField(default=5)),
                ('stock', models.IntegerField(default=50)),
                ('min_stock', models.IntegerField(default=10)),
                ('image', models.TextField(blank=True, default='')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
