# Generated by Django 6.0.7 on 2026-09-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('role', models.CharField(default='Cashier', max_length=50)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('total_orders_handled', models.IntegerField(default=0)),
                ('total_sales_handled', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('availability', models.CharField(default='Available', max_length=30)),
                ('profile_info', models.TextField(blank=True, default='')),
                ('recent_activity', models.CharField(blank=True, default='Clocked in for shift', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
