# Generated by Django 6.0.7 on 2026-09-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, default='Kitchen', max_length=80),
        ),
    ]
