# Generated by Django 6.0.7 on 2026-09-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_api', '0003_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
