// Initial Seed Mock Data for Fast Food Shop Billing & POS System
// Includes signature categories: Briyani, South Indian, Chicken Gravy Varieties, Fast Food, Burgers, Pizza, Tea & Coffee, Drinks, Desserts

export const INITIAL_CATEGORIES = [
  {
    id: 'cat-briyani',
    name: 'Briyani',
    slug: 'briyani',
    icon: 'Flame',
    active: true,
    color: '#ea580c',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Dum & Rice Specials'
  },
  {
    id: 'cat-south-indian',
    name: 'South Indian',
    slug: 'south-indian',
    icon: 'UtensilsCrossed',
    active: true,
    color: '#16a34a',
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Dosa, Idli & Vada'
  },
  {
    id: 'cat-chicken-gravy',
    name: 'Chicken Gravy Varieties',
    slug: 'chicken-gravy',
    icon: 'Soup',
    active: true,
    color: '#dc2626',
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Butter Masala & Chettinad'
  },
  {
    id: 'cat-fast-food',
    name: 'Fast Food',
    slug: 'fast-food',
    icon: 'UtensilsCrossed',
    active: true,
    color: '#f59e0b',
    image: 'https://images.unsplash.com/photo-1561758033-d89a9ad46330?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Burgers, Fries & Snacks'
  },
  {
    id: 'cat-pizza',
    name: 'Pizza',
    slug: 'pizza',
    icon: 'Pizza',
    active: true,
    color: '#ef4444',
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Cheesy Stone Baked'
  },
  {
    id: 'cat-burgers',
    name: 'Burgers',
    slug: 'burgers',
    icon: 'UtensilsCrossed',
    active: true,
    color: '#f97316',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Crispy & Grilled'
  },
  {
    id: 'cat-tea-coffee',
    name: 'Tea & Coffee',
    slug: 'tea-coffee',
    icon: 'Coffee',
    active: true,
    color: '#b45309',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Filter Coffee & Chai'
  },
  {
    id: 'cat-drinks',
    name: 'Drinks & Juices',
    slug: 'drinks',
    icon: 'GlassWater',
    active: true,
    color: '#06b6d4',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Mojitos & Cold Sips'
  },
  {
    id: 'cat-desserts',
    name: 'Desserts & Combos',
    slug: 'desserts',
    icon: 'IceCream',
    active: true,
    color: '#a855f7',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=400&q=80',
    subtitle: 'Brownies & Shakes'
  }
];

export const INITIAL_PRODUCTS = [
  // =================== BRIYANI ===================
  {
    id: 'prod-bir-1',
    name: 'Hyderabadi Chicken Dum Biryani',
    category: 'briyani',
    description: 'Aromatic long-grain basmati layered with tender spiced chicken, saffron, caramelised onions & boiled egg. Served with mirchi ka salan and raita.',
    price: 220,
    costPrice: 90,
    gst: 5,
    stock: 50,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.8,
    ratingCount: 340,
    prepTime: '20-25 mins',
    bestseller: true
  },
  {
    id: 'prod-bir-2',
    name: 'Ambur Special Mutton Biryani',
    category: 'briyani',
    description: 'Traditional seeraga samba rice cooked with tender baby mutton cuts, curd and hand-pounded country spices. Served with dalcha and onion raita.',
    price: 290,
    costPrice: 140,
    gst: 5,
    stock: 35,
    minStock: 8,
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.9,
    ratingCount: 420,
    prepTime: '20-30 mins',
    bestseller: true
  },
  {
    id: 'prod-bir-3',
    name: 'Royal Paneer Tikka Biryani',
    category: 'briyani',
    description: 'Smoky tandoor-roasted paneer cubes layered with saffron basmati rice, fresh mint, fried cashews and aromatic pot spices.',
    price: 190,
    costPrice: 75,
    gst: 5,
    stock: 40,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1642821373181-696a54913e9a?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.6,
    ratingCount: 190,
    prepTime: '15-20 mins',
    bestseller: false
  },
  {
    id: 'prod-bir-4',
    name: 'Chettinad Spicy Egg Biryani',
    category: 'briyani',
    description: 'Flavourful aromatic biryani rice tossed with roasted masala and golden fried boiled eggs, topped with fresh coriander.',
    price: 160,
    costPrice: 60,
    gst: 5,
    stock: 45,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.5,
    ratingCount: 155,
    prepTime: '15-20 mins',
    bestseller: false
  },

  // =================== SOUTH INDIAN ===================
  {
    id: 'prod-si-1',
    name: 'Crispy Mysore Masala Dosa',
    category: 'south-indian',
    description: 'Crisp golden crepe smeared with spicy red garlic chutney, filled with seasoned potato mash. Served with 3 chutneys & piping hot sambar.',
    price: 95,
    costPrice: 28,
    gst: 5,
    stock: 80,
    minStock: 20,
    image: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.8,
    ratingCount: 510,
    prepTime: '10-15 mins',
    bestseller: true
  },
  {
    id: 'prod-si-2',
    name: 'Pure Ghee Roast Paper Dosa',
    category: 'south-indian',
    description: 'Ultra thin, buttery and extra crisp cone dosa roasted generously in pure country ghee. Served with coconut chutney and tangy tomato dip.',
    price: 110,
    costPrice: 35,
    gst: 5,
    stock: 65,
    minStock: 15,
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.7,
    ratingCount: 380,
    prepTime: '10-12 mins',
    bestseller: true
  },
  {
    id: 'prod-si-3',
    name: 'Steaming Idli & Medu Vada Combo',
    category: 'south-indian',
    description: '2 fluffy melt-in-mouth steamed rice idlis + 1 crispy golden lentil vada dipped in drumstick vegetable sambar and coconut chutney.',
    price: 85,
    costPrice: 24,
    gst: 5,
    stock: 90,
    minStock: 25,
    image: 'https://images.unsplash.com/photo-1626074353765-517a681e40be?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.6,
    ratingCount: 290,
    prepTime: '8-10 mins',
    bestseller: false
  },
  {
    id: 'prod-si-4',
    name: 'Ghee Podi Onion Uttapam',
    category: 'south-indian',
    description: 'Thick, spongy fermented pancake topped with juicy chopped shallots, green chillies, fresh coriander & spicy idli gun powder (podi).',
    price: 105,
    costPrice: 30,
    gst: 5,
    stock: 55,
    minStock: 12,
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.5,
    ratingCount: 160,
    prepTime: '12-15 mins',
    bestseller: false
  },

  // =================== CHICKEN GRAVY VARIETIES ===================
  {
    id: 'prod-cg-1',
    name: 'Rich Butter Chicken Masala',
    category: 'chicken-gravy',
    description: 'Tender tandoori chicken pieces simmered in velvety smooth butter, cashew nut paste and fresh cream tomato gravy. Best paired with parotta or rice.',
    price: 240,
    costPrice: 95,
    gst: 5,
    stock: 45,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.9,
    ratingCount: 620,
    prepTime: '15-20 mins',
    bestseller: true
  },
  {
    id: 'prod-cg-2',
    name: 'Chettinad Spicy Chicken Curry',
    category: 'chicken-gravy',
    description: 'Authentic Tamil Nadu village recipe made with fresh stone-ground black pepper, roasted coconut, star anise and tender bone-in chicken.',
    price: 230,
    costPrice: 85,
    gst: 5,
    stock: 40,
    minStock: 8,
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.8,
    ratingCount: 410,
    prepTime: '15-20 mins',
    bestseller: true
  },
  {
    id: 'prod-cg-3',
    name: 'Kadai Chicken Semi-Gravy',
    category: 'chicken-gravy',
    description: 'Juicy chicken wok-tossed with crunchy bell peppers, diced onions, crushed coriander seeds and thick rustic masala gravy.',
    price: 220,
    costPrice: 80,
    gst: 5,
    stock: 35,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1606471191009-63994c53433b?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.7,
    ratingCount: 230,
    prepTime: '15-20 mins',
    bestseller: false
  },
  {
    id: 'prod-cg-4',
    name: 'Smoky Chicken Tikka Masala',
    category: 'chicken-gravy',
    description: 'Succulent boneless chicken tikka cooked in a rich, tangy onion-tomato gravy with roasted kasuri methi and cream.',
    price: 250,
    costPrice: 100,
    gst: 5,
    stock: 30,
    minStock: 8,
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.8,
    ratingCount: 310,
    prepTime: '15-20 mins',
    bestseller: false
  },

  // =================== FAST FOOD ===================
  {
    id: 'prod-ff-1',
    name: 'Loaded Cheesy Peri Peri Fries',
    category: 'fast-food',
    description: 'Crispy skin-on french fries showered in melted cheddar cheese sauce, fiery peri peri spices, chopped jalapenos and garlic herb dip.',
    price: 120,
    costPrice: 38,
    gst: 5,
    stock: 55,
    minStock: 15,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.7,
    ratingCount: 350,
    prepTime: '10-12 mins',
    bestseller: true
  },
  {
    id: 'prod-ff-2',
    name: 'Crunchy Chicken Popcorn (Large)',
    category: 'fast-food',
    description: 'Golden fried tender chicken bite poppers tossed in Cajun seasoning. Served with creamy sweet chilli mayonnaise.',
    price: 140,
    costPrice: 50,
    gst: 5,
    stock: 45,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.8,
    ratingCount: 480,
    prepTime: '10-15 mins',
    bestseller: true
  },
  {
    id: 'prod-ff-3',
    name: 'Classic Salted French Fries',
    category: 'fast-food',
    description: 'Golden crispy potato fingers sprinkled with pure sea salt and served with tangy tomato ketchup.',
    price: 80,
    costPrice: 22,
    gst: 5,
    stock: 60,
    minStock: 15,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.5,
    ratingCount: 210,
    prepTime: '8-10 mins',
    bestseller: false
  },
  {
    id: 'prod-ff-4',
    name: 'Grilled Triple Cheese Sandwich',
    category: 'fast-food',
    description: 'Toasted buttery bread stuffed with mozzarella, English cheddar, sweet corn, capsicum and Italian oregano herbs.',
    price: 90,
    costPrice: 32,
    gst: 5,
    stock: 40,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.6,
    ratingCount: 195,
    prepTime: '10-12 mins',
    bestseller: false
  },

  // =================== BURGERS ===================
  {
    id: 'prod-bg-1',
    name: 'Double Crispy Chicken Zinger Burger',
    category: 'burgers',
    description: 'Two thick crunchy chicken fillets, double cheddar slices, crisp iceberg lettuce and smoky chipotle mayo on toasted sesame buns.',
    price: 160,
    costPrice: 65,
    gst: 5,
    stock: 35,
    minStock: 10,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.8,
    ratingCount: 420,
    prepTime: '12-15 mins',
    bestseller: true
  },
  {
    id: 'prod-bg-2',
    name: 'Veg Supreme Crunchy Burger',
    category: 'burgers',
    description: 'Spiced herb potato patty with melted cheese, fresh tomato slices, crunchy lettuce and creamy garlic herb sauce.',
    price: 90,
    costPrice: 32,
    gst: 5,
    stock: 45,
    minStock: 12,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.5,
    ratingCount: 260,
    prepTime: '10-12 mins',
    bestseller: false
  },

  // =================== PIZZA ===================
  {
    id: 'prod-pz-1',
    name: 'Classic Veg Margherita Pizza',
    category: 'pizza',
    description: '8-inch hand-stretched crust layered with San Marzano tomato basil sauce, 100% real mozzarella and fresh basil drizzle.',
    price: 180,
    costPrice: 65,
    gst: 5,
    stock: 28,
    minStock: 8,
    image: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.7,
    ratingCount: 310,
    prepTime: '15-20 mins',
    bestseller: true
  },
  {
    id: 'prod-pz-2',
    name: 'BBQ Chicken Feast Pizza',
    category: 'pizza',
    description: '8-inch pizza loaded with smoked barbecue chicken chunks, grilled bell peppers, red onions, jalapenos and extra mozzarella.',
    price: 240,
    costPrice: 90,
    gst: 5,
    stock: 22,
    minStock: 6,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.9,
    ratingCount: 390,
    prepTime: '15-20 mins',
    bestseller: true
  },

  // =================== TEA & COFFEE ===================
  {
    id: 'prod-tc-1',
    name: 'South Indian Degree Filter Coffee',
    category: 'tea-coffee',
    description: 'Authentic freshly brewed chicory decoction frothed with rich hot milk in a traditional brass dabarah set.',
    price: 30,
    costPrice: 10,
    gst: 5,
    stock: 100,
    minStock: 25,
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.9,
    ratingCount: 780,
    prepTime: '5-8 mins',
    bestseller: true
  },
  {
    id: 'prod-tc-2',
    name: 'Spicy Masala Cutting Chai',
    category: 'tea-coffee',
    description: 'Strong Assam CTC tea boiled with freshly crushed ginger, green cardamom, cloves and whole milk.',
    price: 20,
    costPrice: 6,
    gst: 5,
    stock: 120,
    minStock: 30,
    image: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.8,
    ratingCount: 650,
    prepTime: '5-8 mins',
    bestseller: true
  },
  {
    id: 'prod-tc-3',
    name: 'Rich Creamy Cold Coffee',
    category: 'tea-coffee',
    description: 'Thick espresso blended with vanilla ice cream, chilled milk and topped with dark Hershey chocolate drizzle.',
    price: 85,
    costPrice: 30,
    gst: 5,
    stock: 45,
    minStock: 12,
    image: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.7,
    ratingCount: 270,
    prepTime: '6-10 mins',
    bestseller: false
  },

  // =================== DRINKS ===================
  {
    id: 'prod-dr-1',
    name: 'Virgin Mint Lime Mojito',
    category: 'drinks',
    description: 'Crisp sparkling club soda muddled with freshly crushed mint leaves, key lime wedges and sweet cane syrup.',
    price: 75,
    costPrice: 22,
    gst: 5,
    stock: 50,
    minStock: 15,
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.7,
    ratingCount: 220,
    prepTime: '5-8 mins',
    bestseller: true
  },
  {
    id: 'prod-dr-2',
    name: 'Fresh Mint Lime Juice',
    category: 'drinks',
    description: 'Zesty hand-squeezed lime cooler with garden mint and a pinch of black salt.',
    price: 50,
    costPrice: 15,
    gst: 5,
    stock: 65,
    minStock: 20,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.6,
    ratingCount: 180,
    prepTime: '5 mins',
    bestseller: false
  },

  // =================== DESSERTS & COMBOS ===================
  {
    id: 'prod-ds-1',
    name: 'Warm Sizzling Chocolate Brownie',
    category: 'desserts',
    description: 'Decadent cocoa walnut fudge brownie served warm with a scoop of vanilla ice cream and molten hot fudge.',
    price: 110,
    costPrice: 38,
    gst: 5,
    stock: 28,
    minStock: 8,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: true,
    rating: 4.9,
    ratingCount: 440,
    prepTime: '8-10 mins',
    bestseller: true
  },
  {
    id: 'prod-ds-2',
    name: 'Supreme Fast Food Duo Combo',
    category: 'desserts',
    description: 'Crispy Double Chicken Burger + Peri Peri Fries + Chilled Mojito Drink.',
    price: 249,
    costPrice: 95,
    gst: 5,
    stock: 30,
    minStock: 8,
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?auto=format&fit=crop&w=600&q=80',
    available: true,
    isVeg: false,
    rating: 4.8,
    ratingCount: 310,
    prepTime: '15-20 mins',
    bestseller: true
  }
];

export const INITIAL_CUSTOMERS = [];

export const INITIAL_ORDERS = [];

export const INITIAL_INVENTORY_LOGS = [];

export const INITIAL_SETTINGS = {
  shop: {
    name: 'BiteCraze Food & Drinks',
    tagline: 'Authentic Biryanis, Curries, Dosa & Fast Food',
    phone: '+91 98765 43210',
    email: 'hello@bitecraze.com',
    address: 'Shop 12, Food Street, Central Avenue',
    gstin: '33AAAAA0000A1Z5',
    fssai: '12423008000123',
    currency: '₹',
  },
  tax: {
    enableGst: true,
    gstRate: 5,
    cgstRate: 2.5,
    sgstRate: 2.5,
  },
  printer: {
    paperSize: '80mm',
    autoPrint: false,
    headerNote: 'Thank You For Dining With Us!',
    footerNote: 'Visit Again! Follow us on Instagram @bitecraze',
  },
};
